/**
 * Promo ~45 s: mismo motor que promo30s, escenas extendidas (+ correas, lab-cta).
 */
import { mountPromo } from './promoCore.js';

/** @type {import('./promoCore.js').PromoScene[]} */
export const SCENES_45 = [
  {
    key: 'home',
    url: 'index.html?promo=1',
    displayUrl: 'themechassist.com',
    ms: 3500,
    frame: 'home',
    title: 'TheMechAssist',
    lead: 'Calculadoras de ingenier\u00eda mec\u00e1nica en la nube.',
    demo: 'home',
    overlay: 'light',
  },
  {
    key: 'machines-hub',
    url: 'machines-hub.html?promo=1',
    displayUrl: 'themechassist.com/machines-hub.html',
    ms: 3000,
    frame: 'hub',
    title: 'M\u00e1quinas y transporte',
    lead: 'Cintas, elevadores, bombas, tornillos\u2026',
    demo: 'machinesHub',
    overlay: 'light',
  },
  {
    key: 'flat',
    url: 'flat-conveyor.html?promo=1',
    displayUrl: 'themechassist.com/flat-conveyor.html',
    ms: 3000,
    frame: 'calc-machine',
    title: 'Datos \u2192 resultados en segundos',
    lead: 'Cinta plana: tensi\u00f3n, potencia y motor.',
    demo: 'flat',
    overlay: 'calc',
  },
  {
    key: 'gears',
    url: 'calc-gears.html?promo=1',
    displayUrl: 'themechassist.com/calc-gears.html',
    ms: 7000,
    frame: 'calc-lab',
    title: 'Transmisi\u00f3n y resistencia',
    lead: 'Par, m\u00f3dulo y dientes \u2014 al vuelo.',
    demo: 'gears',
    overlay: 'calc',
  },
  {
    key: 'belts',
    url: 'calc-belts.html?promo=1',
    displayUrl: 'themechassist.com/calc-belts.html',
    ms: 7000,
    frame: 'calc-lab',
    title: 'Calculadora de correas',
    lead: 'Potencia, RPM y selecci\u00f3n orientativa.',
    demo: 'belts',
    overlay: 'calc',
  },
  {
    key: 'lab-hub',
    url: 'transmission-lab.html?promo=1',
    displayUrl: 'themechassist.com/transmission-lab.html',
    ms: 2500,
    frame: 'hub',
    title: 'Laboratorio de transmisi\u00f3n',
    lead: 'Engranajes, correas, ejes, rodamientos\u2026',
    demo: 'labHub',
    overlay: 'light',
  },
  {
    key: 'hydraulic',
    url: 'calc-hydraulic-cylinder.html?promo=1',
    displayUrl: 'themechassist.com/calc-hydraulic-cylinder.html',
    ms: 6000,
    frame: 'calc-fluid',
    title: 'Hidr\u00e1ulica y neum\u00e1tica',
    lead: 'Cilindros, prensas, bombas.',
    demo: 'hydraulic',
    overlay: 'calc',
  },
  {
    key: 'lab-cta',
    url: 'transmission-lab.html?promo=1',
    displayUrl: 'themechassist.com/transmission-lab.html',
    ms: 2500,
    frame: 'hub',
    title: 'M\u00e1s de 12 calculadoras',
    lead: 'Rodamientos, ejes, ISO, torniller\u00eda\u2026',
    demo: 'labHub',
    overlay: 'light',
  },
  {
    key: 'cta',
    url: null,
    displayUrl: 'themechassist.com',
    ms: 4000,
    frame: 'cta',
    title: 'Empieza gratis',
    lead: 'www.themechassist.com',
    demo: null,
    overlay: 'none',
  },
  {
    key: 'bonus',
    url: 'checkout.html?promo=1',
    displayUrl: 'themechassist.com/checkout.html',
    ms: 6500,
    frame: 'cta',
    title: 'Planes Pro e Ilimitado',
    lead: 'PDF de proyecto, guardado en nube y m\u00e1s calculadoras.',
    demo: null,
    overlay: 'light',
  },
];

export function mountPromo45s() {
  mountPromo(SCENES_45);
}
