/**
 * Presets de casos t�picos (un clic) para p�ginas de m�quinas del hub.
 * Cada entrada: valores coherentes para inputs principales; las p�ginas sincronizan sliders y llaman a refresh.
 */

/** @typedef {Record<string, string|number>} PresetValues */

/** @type {Record<string, { profileHint?: string, values: PresetValues }>} */
export const SCREW_PRESET_BY_ID = Object.freeze({
  food_powder: {
    values: {
      screwCapUnit: 'm3h',
      screwCap: 18,
      screwDiamUnit: 'mm',
      screwDiam: 250,
      screwPitchUnit: 'mm',
      screwPitch: 200,
      screwLength: 8,
      screwAngle: 5,
      screwRho: 550,
      screwTroughLoad: '45',
      screwAbrasive: 'low',
      screwCorrosive: 'low',
      screwMu: 0.32,
      screwBearingEta: 92,
      screwLoadDuty: 'moderate',
    },
  },
  biomass_chip: {
    values: {
      screwCapUnit: 'th',
      screwCap: 12,
      screwDiamUnit: 'mm',
      screwDiam: 400,
      screwPitchUnit: 'mm',
      screwPitch: 320,
      screwLength: 14,
      screwAngle: 12,
      screwRho: 420,
      screwTroughLoad: '30',
      screwAbrasive: 'medium',
      screwCorrosive: 'low',
      screwMu: 0.4,
      screwBearingEta: 90,
      screwLoadDuty: 'moderate',
    },
  },
  cement_slurry: {
    values: {
      screwCapUnit: 'th',
      screwCap: 35,
      screwDiamUnit: 'mm',
      screwDiam: 500,
      screwPitchUnit: 'mm',
      screwPitch: 400,
      screwLength: 22,
      screwAngle: 18,
      screwRho: 1350,
      screwTroughLoad: '15',
      screwAbrasive: 'high',
      screwCorrosive: 'medium',
      screwMu: 0.48,
      screwBearingEta: 88,
      screwLoadDuty: 'heavy',
    },
  },
});

export const INCLINED_PRESET_BY_ID = Object.freeze({
  quarry_short: {
    values: {
      incLength: 35,
      incHeight: 6,
      incAngle: '',
      incLoadMass: 2400,
      incBeltWidth: 0.85,
      incBeltMass: 180,
      incLoadDistribution: 1,
      incBeltSlopePart: 0.92,
      incSpeed: 1.35,
      incFriction: 0.38,
      incEfficiency: 87,
      incRollerD: 630,
      incAdditionalResistance: 800,
      incAccelTime: 4,
      incInertiaFactor: 1.25,
      incDesignStandard: 'ISO5048',
      incLoadDuty: 'moderate',
    },
  },
  sand_wet: {
    values: {
      incLength: 48,
      incHeight: 8,
      incAngle: '',
      incLoadMass: 5200,
      incBeltWidth: 1,
      incBeltMass: 320,
      incLoadDistribution: 1,
      incBeltSlopePart: 0.88,
      incSpeed: 1.1,
      incFriction: 0.48,
      incEfficiency: 86,
      incRollerD: 800,
      incAdditionalResistance: 2200,
      incAccelTime: 5,
      incInertiaFactor: 1.35,
      incDesignStandard: 'CEMA',
      incLoadDuty: 'heavy',
    },
  },
  warehouse_feed: {
    values: {
      incLength: 14,
      incHeight: 2.2,
      incAngle: '',
      incLoadMass: 420,
      incBeltWidth: 0.65,
      incBeltMass: 45,
      incLoadDistribution: 1,
      incBeltSlopePart: 0.95,
      incSpeed: 0.65,
      incFriction: 0.3,
      incEfficiency: 89,
      incRollerD: 320,
      incAdditionalResistance: 120,
      incAccelTime: 2.5,
      incInertiaFactor: 1.12,
      incDesignStandard: 'ISO5048',
      incLoadDuty: 'uniform',
    },
  },
});

export const ROLLER_PRESET_BY_ID = Object.freeze({
  ecommerce_line: {
    values: {
      designStandard: 'ISO5048',
      loadDuty: 'uniform',
      length: 4.5,
      loadMass: 180,
      speed: 0.45,
      rollerD: 76,
      rollerPitch: 120,
      loadSupportMode: 'uniform',
      palletPreset: 'eur1',
      palletOrientation: 'long_along_transport',
      rollingResistance: 0.022,
      efficiency: 92,
      additionalResistance: 25,
      accelTime: 2,
      inertiaFactor: 1.08,
    },
  },
  pallet_distribution: {
    values: {
      designStandard: 'ISO5048',
      loadDuty: 'moderate',
      length: 12,
      loadMass: 1100,
      speed: 0.28,
      rollerD: 89,
      rollerPitch: 125,
      loadSupportMode: 'pallet',
      palletPreset: 'eur1',
      palletOrientation: 'long_along_transport',
      rollingResistance: 0.028,
      efficiency: 90,
      additionalResistance: 180,
      accelTime: 2.8,
      inertiaFactor: 1.12,
    },
  },
  heavy_pallet: {
    values: {
      designStandard: 'CEMA',
      loadDuty: 'heavy',
      length: 8,
      loadMass: 2400,
      speed: 0.22,
      rollerD: 120,
      rollerPitch: 150,
      loadSupportMode: 'pallet',
      palletPreset: 'eur1',
      palletOrientation: 'long_along_transport',
      rollingResistance: 0.035,
      efficiency: 88,
      additionalResistance: 450,
      accelTime: 3.2,
      inertiaFactor: 1.18,
    },
  },
});

export const PUMP_PRESET_BY_ID = Object.freeze({
  chilled_water: {
    values: {
      pumpCalcMode: 'design',
      pumpFlow: 120,
      pumpFlowUnit: 'm3h',
      pumpHead: 32,
      pumpEta: 76,
      fluidType: 'water',
      rho: 1000,
      viscosity: 1.05,
      tempC: 12,
      pumpSpeedRpm: 1450,
      pumpLoadDuty: 'moderate',
      couplingType: 'gearmotor',
      pumpVoltage: 400,
      pumpFreq: 50,
    },
  },
  process_transfer: {
    values: {
      pumpCalcMode: 'design',
      pumpFlow: 65,
      pumpFlowUnit: 'm3h',
      pumpHead: 48,
      pumpEta: 72,
      fluidType: 'brine',
      rho: 1120,
      viscosity: 2.4,
      tempC: 8,
      pumpSpeedRpm: 1455,
      pumpLoadDuty: 'moderate',
      couplingType: 'gearmotor',
      pumpVoltage: 400,
      pumpFreq: 50,
    },
  },
  viscous_duty: {
    values: {
      pumpCalcMode: 'design',
      pumpFlow: 28,
      pumpFlowUnit: 'm3h',
      pumpHead: 22,
      pumpEta: 62,
      fluidType: 'oil',
      rho: 880,
      viscosity: 45,
      tempC: 45,
      pumpSpeedRpm: 960,
      pumpLoadDuty: 'heavy',
      couplingType: 'gearmotor',
      pumpVoltage: 400,
      pumpFreq: 50,
    },
  },
});

export const CAR_LIFT_PRESET_BY_ID = Object.freeze({
  workshop_light: {
    values: {
      clThreadPreset: 'tr32x6',
      clMotorPos: 'top',
      clCapacity: 2800,
      clH: 1.65,
      clT: 55,
      clPitch: 6,
      clD: 32,
      clNutL: 80,
      clMu: 0.11,
      clPallow: 12,
      clSF: 1.25,
    },
  },
  workshop_heavy: {
    values: {
      clThreadPreset: 'tr45x7',
      clMotorPos: 'top',
      clCapacity: 4200,
      clH: 2.1,
      clT: 62,
      clPitch: 7,
      clD: 45,
      clNutL: 110,
      clMu: 0.12,
      clPallow: 10,
      clSF: 1.35,
    },
  },
});

export const TRACTION_PRESET_BY_ID = Object.freeze({
  freight_warehouse: {
    values: {
      teQ: 2000,
      teMc: 1200,
      teKcw: 0.45,
      teH: 12,
      teV: 1,
      teReeving: '1_1',
      teDuty: 'freight',
      teD: 0.55,
      teAlpha: 180,
      teMu: 0.1,
      teMaxN: 6,
    },
  },
  goods_slow: {
    values: {
      teQ: 3200,
      teMc: 2100,
      teKcw: 0.45,
      teH: 8.5,
      teV: 0.63,
      teReeving: '2_1',
      teDuty: 'freight',
      teD: 0.7,
      teAlpha: 200,
      teMu: 0.12,
      teMaxN: 8,
    },
  },
});

export const BUCKET_PRESET_BY_ID = Object.freeze({
  grain_elevator: {
    values: {
      beBucket: 'b3',
      beRho: 780,
      beFluidity: 'good',
      beNature: 'normal',
      beQ: 55,
      beH: 32,
      beDhead: 0.72,
      beDboot: 0.58,
      beVbelt: 1.85,
      beDischargeType: 'centrifugal',
      beWidth: 500,
      beSigma: 315,
      beEta: 0.8,
      beKboot: 0.16,
      beEtaTrans: 0.96,
    },
  },
  minerals: {
    values: {
      beBucket: 'b8',
      beRho: 1450,
      beFluidity: 'poor',
      beNature: 'fragile_abrasive',
      beQ: 120,
      beH: 42,
      beDhead: 0.95,
      beDboot: 0.72,
      beVbelt: 1.55,
      beDischargeType: 'gravity',
      beWidth: 800,
      beSigma: 500,
      beEta: 0.72,
      beKboot: 0.24,
      beEtaTrans: 0.95,
    },
  },
});
